### ISSUE TITLE
Convert problem (encoding)

### ISSUE THREAD

**Issue by oymehus** [adithyabsk/keep2roam#7]
Getting a problem with character encoding. I tried modifying the code by adding an encoding to the open file and the number of files that is converted varies depending on whether I use utf8, utf32 etc., but I am unable to get all files converted with any of the ones I tried.

   # Open the json_file
    with open(json_fpath, "r", encoding='utf8') as f:
        keep_dict = json.load(f)

**Comment by adithyabsk** [comment]
@oymehus Can you give me an example of a file you cannot convert?

**Comment by oymehus** [comment]
Turns out it was only a problem with one of more than 400 files. Attached file imports when the encoding utf8 is added
[9 Rules of Innovation.zip](https://github.com/adithyabsk/keep2roam/files/5862808/9.Rules.of.Innovation.zip)

utf8 encoding that causes problem with other files, eg.
[Klær.zip](https://github.com/adithyabsk/keep2roam/files/5862825/Klaer.zip)

**Comment by adithyabsk** [comment]
@oymehus Not sure what's going on but might it be an OS specific issue? I cannot seem to repro the error on my mac.

Sorry it took me a bit to get back to you.

**Comment by adithyabsk** [comment]
Okay I'm closing for now, if this is still a problem feel free to ping this thread.
